### PR TITLE
[v1.0][F12-B3] Media Socializer

### PR DESCRIPTION
**Pull request by shadow2496**
@Nethergale @KevinChuangCH

### CODE REVIEW

**Comment by OuyangDanwen** [comment]
@shadow2496 @KevinChuangCH  Please check your code styling. As mentioned it is advised not to submit PRs without passing travis.

**Comment by KevinChuangCH** [comment]
@OuyangDanwen This pull request was sent before Travis was set up for our team repo. So we did not see the fail check on Travis when we create the PR.
The Travis for our team repo has being set up and we are working on correcting all the previous PR now.

**Comment by KevinChuangCH** [comment]
@OuyangDanwen After checking through the failed Travis test, we realised that the test failed because of a commit that is not ours.
(Link to the commit: https://github.com/nus-cs2103-AY1718S2/addressbook-level4/commit/e953ce0f997f937c6c21fc486e07e7e83b9fef65)

Is this because we did not setup our team CI before editing?

**Comment by Zhiyuan-Amos** [comment]
(upstream dev here) @OuyangDanwen weirdly, I verified that their [repo](https://github.com/CS2103JAN2018-F12-B3/main) passes Travis-CI, but this PR fails the Travis-CI check. Maybe can try restarting the Travis-CI build?

> we realised that the test failed because of a commit that is not ours.

@KevinChuangCH, I don't think this is the reason because this commit isn't in your repo's commit history :P 

Edit: According to prof's comment below, it seems that Travis is building the wrong PR; it's building from  e953ce0 instead of your PR.

**Comment by damithc** [comment]
> Maybe can try restarting the Travis-CI build?

I've done that once, but still fails.

**Comment by damithc** [comment]
May be try closing this PR and opening another PR, in case it's Travis issue that is peculiar to this PR only?

**Comment by shadow2496** [comment]
@Zhiyuan-Amos, I think that is the reason. Travis tests the commit that is not ours.
image

**Comment by shadow2496** [comment]
@Zhiyuan-Amos, @damithc, I will open another PR. Thank you for your help!

**Pull request closed without merging**
